### ISSUE TITLE
"Allow Enclave Computations" option is missing

### ISSUE THREAD

**Issue by thuannguy** [MicrosoftDocs/sql-docs#2376]
I did all steps successfully until "Step 5: Provision enclave-enabled keys" where the "Allow Enclave Computations" option doesn't show up for me. Are there some missing steps that I need to do?

OS: Windows Server 2019 data center.
SQL Server 2019 CTP3 Eval - Developer version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f498ebf8-8cda-7e68-c70c-9ecd0e7bd7df
* Version Independent ID: b710fea4-0d4e-5fdd-03e8-ce2679fa18c2
* Content: [Tutorial: Getting Started with Always Encrypted with secure enclaves using SSMS - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/tutorial-getting-started-with-always-encrypted-enclaves.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @jaszymas
* Microsoft Alias: **jaszymas**

**Comment by thuannguy** [comment]
I got this very same error: https://social.msdn.microsoft.com/Forums/en-US/e5fd5f37-077d-4460-9d79-c663ad6f714f/sql-2019-missing-quotallow-enclave-computationsquot-amp-no-enclave-provider-found-for?forum=sqlsecurity

Information of my environment:
SQL Server Management Studio						15.0.18131.0 (v18.1)
Microsoft Analysis Services Client Tools						15.0.1347.0
Microsoft Data Access Components (MDAC)						10.0.17763.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.17763.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.17763

**Comment by jaszymas** [comment]
You have mostly likely encountered the bug, which is documented in the release notes at: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-ver15-release-notes?view=sqlallproducts-allversions#loading-enclave-fails. The bug causes a failure when loading the enclave library. The checkbox does not appear in SSMS, because the server does not have an active enclave (due to the bug).

We have fixed this issue in the upcoming CTP 3.1 that will ship soon. Once it is released, please install it on your SQL machine, and you should be able to resume the tutorial.

**Comment by MightyPen** [comment]
The fine answer provided by jaszymas constitutes a Fix for this Issue 2376. Closing now.

@thuannguy  Thank you for submitting this Issue. We hope to hear from you again.

The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

**Comment by thuannguy** [comment]
@MightyPen 
https://github.com/MicrosoftDocs/sql-docs/commit/419f46ae2012bce65d670e40457aeb77256307a8#diff-171b0d35ed7df7953cc87e9c7b78bd08
It seems that the release note was updated yesterday and the part about that security enclave loading bug was removed. Is it still included in CTP 3.1?

**Comment by MightyPen** [comment]
@thuannguy I am unsure what you meant by the word "it".  But our proper practice is the treat the Release Notes as true, partly because they are well scrutinized before being published.

In this particular case, the previous text about the bug was deliberately removed.  Personally I take that to mean that the bug is fixed in CTP 3.1. It would be unusual for us to keep a list of old fixed bugs from old CTP versions in the Release Notes of the latest CTP release.  I have no reason to doubt my conclusion that the bug is fixed in CTP 3.1, but again for official statements, the Release Notes is the official word.

If you see something that is wrong about the Release Notes, please let us know.
Thanks.

**Comment by jaszymas** [comment]
Yes, the bug was fixed in CTP 3.1 (as I indicated earlier), and that's why the corresponding entry was removed from the release notes.

**Comment by thuannguy** [comment]
thank you for your swift response. I can confirm that CTP 3.1 fixes my issue 😄

**Comment by MNashDev** [comment]
We are running on Microsoft SQL Server 2019 (RC1) - 15.0.1900.25 (X64)  Developer Edition and are still unable to follow Step 5 due to enlave errors.

We are also seeing 'Internal enclave error: Cannot initialize the VBS enclave. Load method: 敇䕴据慬敶' in the Event Logs.

We've been told thet CTP 3.1 should have been included in 15.0.1900.25 but we're still hitting this issue.

**Comment by MightyPen** [comment]
Newer Issue #3414 is a continuation of this Issue #2376 .
