### ISSUE TITLE
The document states that current_timezone() is available in SQL Server 2017 (and Azure  SQL Database) but on SQL Server 2017 it results in an error

### ISSUE THREAD

**Issue by djwarsop** [MicrosoftDocs/sql-docs#3025]
On SQL Server 2017 (developer edition):

begin
	select @@version;
end;
go
begin
	select CURRENT_TIMEZONE();
end;
go

Results in:

Microsoft SQL Server 2017 (RTM-CU15-GDR) (KB4505225) - 14.0.3192.2 (X64) 
	Jun 15 2019 00:45:05 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 &lt;X64&gt; (Build 9600: )

(1 row affected)

Msg 195, Level 15, State 10, Line 6
'CURRENT_TIMEZONE' is not a recognized built-in function name.

It works as documented on Azure SQL Database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a2fcc8-dff8-e3fb-2c3c-7521b6c9798b
* Version Independent ID: a2c8ff06-a32f-79f4-d7a4-0a7f72ba3d95
* Content: [CURRENT_TIMEZONE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/current-timezone-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/current-timezone-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/current-timezone-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by WilliamAntonRohm** [comment]
@djwarsop -- thank you for your feedback.

@MladjoA -- please look into this issue 3025.

**Comment by MladjoA** [comment]
CURRENT_TIMEZONE actually hasn't been ported to previous versions of SQL Server yet.
I will make correction in the function availability statement and let you know once published.

**Comment by bdcoder2** [comment]
Using: 
Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64) Apr 29 2016 23:23:58 Copyright (c) Microsoft Corporation Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 (Build 9600: ) (Hypervisor)

When I issue:
SELECT CURRENT_TIMEZONE();  

System responds with:
'CURRENT_TIMEZONE' is not a recognized built-in function name.

**Comment by dvansteenburg** [comment]
The value returned by CURRENT_TIMEZONE cannot be used with "AT TIME ZONE", nor is it listed in sys.time_zone_info.  As such, it is not useful for converting other date's times to the instance's local time.

Example:
DECLARE @tzstr NVARCHAR(128) = current_timezone()
SELECT * FROM sys.time_zone_info WHERE name = @tzstr
SELECT @tzstr
SELECT SYSUTCDATETIME() AT TIME ZONE 'UTC'
	, (SYSUTCDATETIME() AT TIME ZONE 'UTC') AT TIME ZONE @tzstr
GO

name                                                                                                                             current_utc_offset is_currently_dst
-------------------------------------------------------------------------------------------------------------------------------- ------------------ ----------------

(0 rows affected)


--------------------------------------------------------------------------------------------------------------------------------
(UTC-06:00) Central Time (US & Canada)

(1 row affected)

                                   
---------------------------------- ----------------------------------
Msg 9820, Level 16, State 1, Line 7
The time zone parameter '(UTC-06:00) Central Time (US & Canada)' provided to AT TIME ZONE clause is invalid.

**Comment by MladjoA** [comment]
@WilliamAntonRohm , supported versions section is now fixed.

**Comment by WilliamAntonRohm** [comment]
@MladjoA -- thank you.

**Comment by sam-s4s** [comment]
This is still a problem...
https://docs.microsoft.com/en-us/sql/t-sql/functions/current-timezone-transact-sql?view=sql-server-2016

(it shouldn't be listed under 2016)

Also I always find it difficult to find the supported version on the docs website. I feel like every function/feature should have a "supported versions" list somewhere, but can never find one.

**Comment by MladjoA** [comment]
@sam-s4s , I followed the link you shared and "Applies to" section on the top of the document shows only Azure SQL Database and Azure SQL Managed Instance as supported platforms. Can you please elaborate where's the issue? Thanks

**Comment by sam-s4s** [comment]
> @sam-s4s , I followed the link you shared and "Applies to" section on the top of the document shows only Azure SQL Database and Azure SQL Managed Instance as supported platforms. Can you please elaborate where's the issue? Thanks

Sorry I might be getting confused - but that link is FOR 2016. As in, SQL 2016 is selected in the drop down menu on the left. Implying that the documentation is targeted for that version. Which we know is not true, because that function does not exist for 2016.
