### ISSUE TITLE
setMsiClientId is misspelled

### ISSUE THREAD

**Issue by kamattson** [MicrosoftDocs/sql-docs#4978]
Code is misspelled:
 ds.setMsiClientId("...."); // Replace with Client ID of User-Assigned MSI to be used

Should be:
 ds.setMSIClientId("..."); // Replace with Client ID of User-Assigned MSI to be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8816308-e8ba-e813-6607-473bd3e9aeeb
* Version Independent ID: 7724b453-99b2-4567-e0d1-6ccb9d83e83d
* Content: [Connecting using Azure Active Directory authentication - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15)
* Content Source: [docs/connect/jdbc/connecting-using-azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/connecting-using-azure-active-directory-authentication.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@kamattson -- Kris, thank you for your feedback.  I am looking into this article.

**Comment by David-Engel** [comment]
This has been fixed.

#please-close

**Comment by yaja0612** [comment]
This issue still valid for com.microsoft.sqlserver:mssql-jdbc:7.4.1.jre8 atleast (though mentioned above 7.2 in documentation

**Comment by WilliamAntonRohm** [comment]
@yaja0612 -- thank you for your feedback.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
Found another instance of "setMsiClientId" in the doc and changed it to "setMSIClientId". This should be reflected in tomorrow morning's (PST) publish to the docs website.

#please-close
